### ISSUE TITLE
Document procedures that only exist in our heads

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#100]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 

# Background

### Feature request 
We have a bunch of procedural and policy documentation that we have decided on but is not documented anywhere.
**What does it do?**:
Add documentation.
**Does it need new or changed commands? What are they?**:
No.
**Does this feature affect other parts of TigerOS?**:
No.

# Details

* **Stacktrace** (if applicable):

**Comment by ct-martin** [comment]
Added to wiki (with approval from @axk4545 ):
* Policy for adding new members
* Splitting of the web server and build host
* Policy for access to the web server and build host

Closing issue
