### ISSUE TITLE
GNOME Screenshots

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#103]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
Currently there are no screenshots available for the GNOME Desktop Environment. 

# Background

### Feature request 

**What does it do?**:
Allows users to have an understanding of what the GNOME Desktop Environment looks like.

**Does it need new or changed commands? What are they?**:
No

**Does this feature affect other parts of TigerOS?**:
No

# Details
I need to know which pictures would look best for screenshots. Please leave comments below as to what portions of the DE you would like displayed.

**Comment by Tjzabel** [comment]
![tigeros_dark](https://user-images.githubusercontent.com/22552344/38164837-83c1e2ea-34d8-11e8-92aa-88f02ae2c750.png)

![tigeros_tweaks](https://user-images.githubusercontent.com/22552344/38164839-870d47b4-34d8-11e8-821f-c85652539200.png)

![tigeros_orange_background](https://user-images.githubusercontent.com/22552344/38164841-945fb730-34d8-11e8-8016-b7ac56003b18.png)

![tigeros_website](https://user-images.githubusercontent.com/22552344/38164842-9b076d1c-34d8-11e8-972d-f6f49466abaa.png)

**Comment by Tjzabel** [comment]
@ct-martin @axk4545 @gen1e Any further screenshots you would like to have for TigerOS?

**Comment by axk4545** [comment]
I can't think of any off the top of my head...

**Comment by jflory7** [comment]
@Tjzabel I like all the ones you provided. I would sort the images on the website based on the outcome of #109, so the default appears first.

I might also include a screenshot of the install scripts to pull RIT-related applications. Even if it isn't super pretty and fancy, the functionality is there and it is cool.
