### ISSUE TITLE
Add IRC channel to website

### ISSUE THREAD

**Issue by jwflory** [RITlug/TigerOS#108]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: Add the `#rit-tigeros` channel to the website, so other people interested in the project can find out where development discussion is

# Background

It will help direct interested people in the project to the development discussion channel to ask questions or contribute to the project. Currently on the website, there is no mention of the IRC channel or where to go and ask questions.

# Details

This could go in the _What is TigerOS?_ part of the website near the top.

Example:

**Join the conversation! Find us on [#rit-tigeros](https://webchat.freenode.net/?channels=rit-tigeros) on the [Freenode IRC network](https://freenode.net/) for development discussions and support.**

**Comment by Tjzabel** [comment]
@jflory7 Great issue. I am not entirely sure where the best place to host information on how to get in touch with the devel team. I don't particularly like adding the IRC tag to the "What is TigerOS" section because I don't feel it fits there.

Another possible location could be underneath the RITlug  | GitHub | Open Source section? Our website is going to be updated in the near future. Most portions available are out of date or don't work.

**Comment by axk4545** [comment]
Moved to wiki and README. thoughts @jflory7 ?

**Comment by jflory7** [comment]
@axk4545 I don't see anything new on the website yet.

**Comment by axk4545** [comment]
@jflory7 We put it in the wiki instead and linked the wiki from the website.

**Comment by jflory7** [comment]
@axk4545 I think the wiki and contact information are two different things. I recommend adding a specific link to contact info to the site, even if it is its own wiki page.

**Comment by axk4545** [comment]
@jflory7 ok. will figure out where that goes.

**Comment by Tjzabel** [comment]
Added per 2b7188f1

**Comment by jflory7** [comment]
I thought about this a bit, and I think a link to the IRC should also go in the header / menu bar. A link to the `#rit-tigeros` Freenode web chat is enough.

https://webchat.freenode.net/?channels=rit-tigeros

**Comment by Tjzabel** [comment]
@jflory7 Are you thinking more of a "Contact Us" header that points to the irc channel?

**Comment by ct-martin** [comment]
This is on the TigerOS page on the RITlug website, which will be used as a basis for the new website.
