### ISSUE TITLE
Default TigerOS Look

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#109]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [ ] Other issue
    * [X] Question 
* **Describe the issue / feature in 1-2 sentences**: 
Currently we have two default UI looks. The first is an orange wallpaper with the arc-dark theme.
The second look is a dark wallpaper with a default dark gnome theme. 

# Background

### Feature request 

**What does it do?**:
Allows for the creation of the standard TigerOS look.

**Does it need new or changed commands? What are they?**:
No

**Does this feature affect other parts of TigerOS?**:
May potentially affect future UI development.

# Details

### Option 1 - Orange theme
![tigeros_tweaks](https://user-images.githubusercontent.com/22552344/38164743-f1754fea-34d6-11e8-89e8-d08174b51cec.png)

### Option 2 - Dark theme
![tigeros_dark](https://user-images.githubusercontent.com/22552344/38164759-1979b60c-34d7-11e8-8611-cf0a593124fd.png)

**Comment by axk4545** [comment]
Personally I like the first option

**Comment by jflory7** [comment]
I also prefer the first option.

**Comment by Tjzabel** [comment]
We have gone with the first, orange theme.
