### ISSUE TITLE
Remove dash-to-dock repackaging from RITlug repositories and mirrors website

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#113]
# Summary
Since repackaging dash-to-dock, an official RPM has been created for this package. Thus, our repackage is now no longer necessary. 

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [X] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 

# Details
The builder.ritlug.com website also currently hosts the repkg dash-to-dock. This can be removed due to the new [dash-to-dock](https://github.com/RITlug/tigeros-dash-to-dock "TigerOS dash-to-dock") package no longer needing this repackage.

**Comment by axk4545** [comment]
Done.
