### ISSUE TITLE
Create TigerOS Website "About Us" Page

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#121]
We only need to write the content not the HTML. Pass on to @ct-martin for translation to HTML.

**Comment by ct-martin** [comment]
Temporary solution; doesn't fulfill the goal of the issue. Reopening and moving to beta milestone

**Comment by Tjzabel** [comment]
TigerOS is currently a part of the main RITlug website. Closing as currently infeasible.
