### ISSUE TITLE
Plan exhibit for Imagine RIT on Saturday, April 28

### ISSUE THREAD

**Issue by jflory7** [RITlug/TigerOS#123]
The TigerOS team needs to plan how they want to demo and exhibit the project at Imagine RIT later this month. For more info about RITlug's presence at Imagine RIT, see RITlug/tasks#38.

**Comment by axk4545** [comment]
We will cover this at the meeting on Wednesday.

**Comment by Tjzabel** [comment]
# ImagineRIT Necessities

* Monitor
  * @Tjzabel
* Powersupply/powerstrip
* Spare laptop with TigerOS displaying
  * @Tjzabel or @axk4545 
* Keyboard?
  * @Tjzabel may possibly be able to provide

### Footnote
**@axk4545 will be out of town**
* _Laptop will be handed off before he leaves_

**Comment by ct-martin** [comment]
@Tjzabel is going to do a fresh install on his spare laptop tonight/tomorrow and @axk4545 and I will take a quick second-person look

**Comment by ct-martin** [comment]
Quick fix tickets: #131 & #132

**Comment by Tjzabel** [comment]
ImagineRIT went well :+1:
