### ISSUE TITLE
Cleanup branches and codebase to match current progress

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#127]
Remove old branches and docs to match the current state of the project.

**Comment by Tjzabel** [comment]
With this issue, it may be time to move the fedora-28 branch into devel since the ISO build was successful. We would then delete all other branches, leaving `master` and `devel`.

**Comment by ct-martin** [comment]
There's a branch with my docker testing which I think would be worthwhile
to keep, although I need to look to see which branch that was

**Comment by axk4545** [comment]
@ct-martin looking at the branches and when they were last updated I think it is this one: https://github.com/RITlug/TigerOS/tree/nightly/build-scripts

**Comment by Tjzabel** [comment]
I will work with @ct-martin in order to integrate [my GitLab fork](https://gitlab.com/Tjzabel/TigerOS) into the main TigerOS repository. My fork is currently the latest stable version of TigerOS, and it is critical we add this soon back upstream so others can follow our progress.

**Comment by Tjzabel** [comment]
[This PR](https://github.com/RITlug/TigerOS/pull/142) makes the devel branch up to date, and will allow for the deletion of the fedora-28 branch.

**Comment by Tjzabel** [comment]
@ct-martin I would like to delete the fedora-28, devel-f27, and nightly branches. Fedora-28 and devel-f27 seem to be able to be removed easily. You had said there are some docker changes you wanted to salvage in the nightly branches. 

I know this is a busy week so let me know how things are going :+1:

**Comment by Tjzabel** [comment]
So, at this point this issue is almost complete.

I've made devel even with the F28 updates. Also, there now exists a `fedora-29` branch, which is also complete.

It is now up to @ct-martin if he wants to keep the nightly branches or not. I've added all the docker scripts into the [Fedora 29](https://github.com/RITlug/TigerOS/tree/fedora-29/build-scripts) branch.

**Comment by Tjzabel** [comment]
Completed :+1:
