### ISSUE TITLE
CS setup script for 3rd party programs

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#13]
Create script to install following packages.
- Intellij
- Pycharm Edu edition
- racket(wget source from [here](https://mirror.racket-lang.org/installers/6.8/racket-6.8-src.tgz) and build 
- prolog
- logisim jar
- my wget script to fetch assignments https://github.com/axk4545/linux-stuff/blob/master/fetch 
- JFLAP(http://www.jflap.org/jflaptmp/may15-2011/withoutSource/JFLAP.jar) see license http://www.cs.duke.edu/csed/jflap/jflaptmp/aug28-09/license.html for conditions

**Comment by axk4545** [comment]
@Josh1147582 next steps: simple scripts to pull in other packages or one script that runs all tasks to install CS packages. Probably keep the jar file ones standalone and call from main script.
Let me know if you like this approach.

**Comment by axk4545** [comment]
RE file locations apparently Linux has a dedicated location for the jar files that are part of applications. it is /usr/share/java/[jar file]. I am happy to do some work on the scripts after we pull in your changes to the main repo.

**Comment by axk4545** [comment]
So it looks like we can make it an rpm but we will need to build the jar inside the RPM package to comply with Fedora guidelines. I am going to try one for jgrasp using https://fedora-java.github.io/howto/24/index.html#_example_rpm_project as a base

**Comment by axk4545** [comment]
@Josh1147582 intellij seems to generate a launch script and desktop file on first run so we would just need to deal with putting the parts in the right places so that they aren't running it from one directory.

**Comment by axk4545** [comment]
updated initial comment please read.

**Comment by Josh1147582** [comment]
So something like: 

`./rit-install.sh <major> <package(s)>`?

**Comment by axk4545** [comment]
So the way I have written the [postinstall script](url), it is  based on case statements. The case for CS is currently structured so that you would call each script to install the programs sequentially exiting at the end of each script. You could optionally work in logic to allow the user to install only some programs.

**Comment by axk4545** [comment]
ok. so just checking we still have pycharm, logisim racket and prolog right?

**Comment by axk4545** [comment]
Closing this. @Josh1147582 please open an issue for prolog with appropriate context.
