### ISSUE TITLE
Further UI Additions

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#132]
* [x] Overpass as font
* [x] Show date
* [x] 12-hour time
* [x] Battery %

**Comment by Tjzabel** [comment]
I would like to move this issue to the general Beta release once these "quick fixes" have been established

**Comment by ct-martin** [comment]
@Tjzabel Since we were talking about it at FOSS Hours and a couple of these already had related tickets (#77, #46) I had assumed you wanted to do these for ImagineRIT. If you don't have time to get to it, just change the milestone.

**Comment by Tjzabel** [comment]
## Update

UI additions have been added into [TigerOS UI Tweaks](https://github.com/RITlug/tigeros-ui-tweaks)!

Closing issue.
