### ISSUE TITLE
Add Computer Engineering Major Software

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#135]
There is currently no software section for the CE major. Please comment below a list of all packages/programs supported by linux.

**Comment by Tjzabel** [comment]
Pycharm, IntelliJ IDEA. CE seems to be a windows-centric major, so this may be hard to implement.

**Comment by justwheel** [comment]
Which major is CE? Computer Engineering?

**Comment by ct-martin** [comment]
@jwflory yes

**Comment by Tjzabel** [comment]
@jwflory yep! I should update the name to reflect this. I realized many people may not know what this major refers to.
