### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#137]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
The current state of the README only tailors towards developers who wish to get involved and build their own ISO. We need to cater towards our current audience and start the README with instructions on how to download the ISO, and install TigerOS on their own machine.

# Background

There have been a few comments from others who have wanted to download TigerOS on their own machine, but when checking out the repo, discovered the README only includes developer instructions.

### Feature request 

**What does it do?**:
Provides clear instructions on how to install TigerOS.

**Does this feature affect other parts of TigerOS?**:
Nope

**Comment by ct-martin** [comment]
I think we should just remove the instructions from the readme and put them in the wiki clearly

**Comment by gen1e** [comment]
Also I think the README should reference the wiki so people know to check there for info. I don't think it's explicitly in the README at all, most people know to check the README but I feel less think to check the GitHub wiki.

**Comment by Tjzabel** [comment]
In addition to all of these comments, I believe it would be helpful to show a general idea of what TigerOS is. To do this, I would like to have a summary of what makes TigerOS worthy of a remix, and also show off some of the screenshots we have. 

The README should be an introduction for potential users, _not_ for prospective developers. However, we should have a developers section of the README at the end to point contributors in the right direction on how to properly help.

Let me know if you agree with any of the above.

**Comment by Tjzabel** [comment]
I am blocking this issue on the new website being completed, so we know where we stand on documentation and what we need to add into the README.

**Comment by Tjzabel** [comment]
As a side note, it would be a good idea to merge the [UI Tweaks](https://github.com/RITlug/tigeros-ui-tweaks/blob/master/README.md) README into the overall TigerOS README. That way, users can get a much better idea right off the bat what TigerOS looks like.

**Comment by Tjzabel** [comment]
This is essentially done (on GitLab's side).
