### ISSUE TITLE
Upgrade to Fedora 28

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#138]

**Comment by ct-martin** [comment]
To-do:
* [ ] Rebuild packages (inc. version numbers and putting on mirror)
* [ ] Bump version in build scripts & kick-starts
* [ ] Start ISO build and hide behind a table

**Comment by Tjzabel** [comment]
At the moment, I've create an F28 branch with a version bump in the build scripts. 

RPM package bumps will be done slowly over the coming week(s).

**Comment by Tjzabel** [comment]
## Result

TigerOS 28 ISO creation succeeded! Closing this issue.
