### ISSUE TITLE
Document Fedora Upgrade Process

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#139]
Currently we are upgrading to Fedora 28. However, we don't have a process on how to properly do this. 

It would be nice if we had the documentation available to look at with each 6-month release cycle Fedora follows.

**Comment by Tjzabel** [comment]
TigerOS 28 ISO build succeeded! Here's the process we followed:

1. Create fedora-# branch
1. Update build scripts to reflect wanted version
1. Go through each RPM package and update versions when necessary
1. Create new version directory on mirror
1. Sign new packages, upload to new mirror directory
1. Build ISO
1. Test ISO
1. If everything goes as planned, merge fedora-# branch to master!

**Comment by Tjzabel** [comment]
Blocked on #120

**Comment by ct-martin** [comment]
@Tjzabel please use the GitHub wiki and the content will be merged when the site is created

**Comment by Tjzabel** [comment]
TigerOS upgrade process has been described in the [wiki](https://github.com/RITlug/TigerOS/wiki/TigerOS-Upgrade-Process) in the meantime, while the TigerOS website undergoes a redesign
