### ISSUE TITLE
jGrasp installer script

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#14]
Write a script to download jGrasp from http://www.jgrasp.org/dl4g/jgrasp/jgrasp203_05.zip and install it to the appropriate directory in /usr/local/

**Comment by KevinMGranger** [comment]
I recommend setting up a proper [COPR](https://fedoraproject.org/wiki/Category:Copr) and making that easy to use instead.

**Comment by axk4545** [comment]
Licensing prevents packaged redistribution. The script will need to be run as part of a post install setup or in another way by the user.

**Comment by axk4545** [comment]
See https://fedoraproject.org/wiki/Packaging:Java#JAR_file_installation for guidance on file naming and locations. jar file itself should go in /usr/share/java/[jar file]

**Comment by axk4545** [comment]
For now just wget extract to /opt/jgrasp and put a launcher script in /usr/bin named jgrasp that will run the jar. Also create a .desktop file for desktop menus. see the jflap script for locations and as a reference

**Comment by axk4545** [comment]
Looks like this may just need to be really clear instructions on downloading and installing jGRASP to avoid legal stupidity. grr.

**Comment by axk4545** [comment]
@nathaniel486 closing this. see the postinstall script.
