### ISSUE TITLE
Make licensing clear in all source files

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#143]
# Summary
Having the GPLv3 as our main license, it is strongly suggested to include the GPL header within each source file. As far as I know, we only include the license file within each directory, and not in the contained source files.

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [X] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
TigerOS source files do not contain license headers

**Comment by axk4545** [comment]
We should take care to ensure that the upstream things we use retain their
licences. The stuff from Fedora is a mix of MIT  and GPL IIRC.

**Comment by Tjzabel** [comment]
@axk4545 yep. I believe anything Fedora-related should already have the required licensing. This is more for source files *we* have created.

**Comment by Tjzabel** [comment]
Anything upstream is not our problem, unless we decide to report it to them

**Comment by axk4545** [comment]
My comment was more about ensuring compatibility of licenses

On Sep 28, 2018 4:35 PM, "Tim Zabel" <notifications@github.com> wrote:

Anything upstream is not our problem, unless we decide to report it to them

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RITlug/TigerOS/issues/143#issuecomment-425558358>, or mute
the thread

**Comment by Tjzabel** [comment]
I will take up this issue within the next few days :+1:

**Comment by Tjzabel** [comment]
### Update

This issue is part of #144. As I am going through each RPM package, I am looking at the source files if they are present, and making sure there are license headers within each of the files.

**Comment by Tjzabel** [comment]
### GPLv3 Source Header
```
<file name>

Copyright (C) 2018  RIT Linux Users Group  All rights reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```
@ct-martin @axk4545 please let me know if you are okay with adding this license header to all created source code.

**Comment by ct-martin** [comment]
@Tjzabel that looks good to me. I'm more concerned about the repackaged software and backgrounds personally since their licenses are mixed. Part of this issue was also that after the repos got split up the new repos didn't all get labeled clearly, which a normal license file can fix too. Both this and license files are good to me.

**Comment by Tjzabel** [comment]
@ct-martin thanks for the feedback.

Regardless, we still need(ed) license headers within our own source files as well. I'm currently in the process of doing this as I go along.

**Comment by Tjzabel** [comment]
### Update
This process is just about complete. As I've been going through and updating all of our RPM packages, I've taken the liberty to add license headers to all source code that needed it. I don't think there is anything we can possibly do for the repackaged software. The `License:` tag in the spec files are the same license the repackaged software is under, so I'm leaving it at that.

**Comment by ct-martin** [comment]
@Tjzabel just to double-triple-check you got looped in, @gen1e and I need to talk about backgrounds before this issue can be closed

**Comment by Tjzabel** [comment]
@ct-martin this issue is for source code. 

Backgrounds is part of #141 is what I understand.

**Comment by ct-martin** [comment]
@Tjzabel that issue was for docs, but if you want to adjust the scopes and close this issue then go ahead

**Comment by Tjzabel** [comment]
### Update
As I've gone through updating all the packages to Fedora 29, I've looked at and updated all scripts to include their proper licensing where applicable.

I am leaving this issue open until all packages are signed and uploaded to the mirror, and all RPM package repositories are cleaned up. Currently, the repositories are dirty and updates have not been pushed to GitHub.

**Comment by Tjzabel** [comment]
This has been taken care of after doing the F29 build in all packages.

**Comment by Tjzabel** [comment]
### Reopening Issue
Although scripts packages have been updated, the core portion of this issue has not yet been addressed.

### Next Steps
The goal of the scripts package is to be able to install all tigeros packages through dnf. So, for `tigeros-repkg-jflap`, we should be able to install with `dnf install`. 

@ct-martin is going to update this issue with a more proper name to reflect these changes.
