### ISSUE TITLE
Upgrade to Fedora 29

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#144]
Fedora 29 is scheduled to come out late October. We should have a Fedora 29 release not long after.

Here are the steps we need to take to complete this task:

1. ~Create Fedora 29 branch~
2. ~Update all version variables to F29~
3. ~Create an F29 directory on the [TigerOS Mirror](https://mirrors.ritlug.com/TigerOS/)~
4. ~Upgrade all RPM packages to F29~
5. ~Sign all F29 packages and place on mirror~
6. ~Generate F29 ISO build~
7. Test build
8. Put on mirror

**Comment by ct-martin** [comment]
29 folder created on mirror

**Comment by Tjzabel** [comment]
### Update
I have been very busy the past few weeks, and so I apologize for not getting much progress done with this issue. 

I am still working locally on converting all packages over to F29. The main hurdle isn't doing the package upgrades, but figuring out ways to do this process via our CI.

If you would like, I can simply upgrade all these packages without trying to figure out any CI, so that way we can move forward with the F29 release.

**Comment by ct-martin** [comment]
For the sake of building, please upload them to the signing folder on the
builder. If you have a draft .gitlab_ci.yml file I can test it with CI
and/or tweak a bit to match the new process.

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment]
@ct-martin sounds good. I'll forgo working on the CI and just get the packages updated.

**Comment by Tjzabel** [comment]
So, final update.

There are 2-3 more packages that need updating. The goal is to have the Fedora 29 upgrade process done by the end of this weekend. 

I had totally forgotten we were going for an end-of-October beta release :-)

**Comment by justwheel** [comment]
> I had totally forgotten we were going for an end-of-October beta release :-)

Spook-tacular! :bat: :jack_o_lantern: :candy:

**Comment by Tjzabel** [comment]
### Update
All packages have been upgraded to Fedora 29, except for the `tigeros-repkg-logisim` package. 
There seems to be an issue with a download file, and the build process fails. This may be an issue with the actual package itself, and will need to be looked into.

**Comment by Tjzabel** [comment]
All packages upgraded to F29!

Current work to be done is to sign all packages, put them on F29 dir on mirror, and do ISO build :+1:

**Comment by Tjzabel** [comment]
All packages are on the [F29 mirror](https://mirrors.ritlug.com/TigerOS/29/packages/x86_64/).
We're all set to go with building the F29 ISO.

As an added challenge, I'm doing the ISO build with the new Dockerfile we have.

**Comment by Tjzabel** [comment]
We had an issue with the GPG key we created for the F29 release, but everything looks all good now. Current plans are to have the latest ISO build done tonight.

**Comment by Tjzabel** [comment]
### Update
Currently, we are on the "test build" stage. The ISO has been built successfully, and now it is time to test the new changes.

At this time, there are some big/odd issues with TigerOS, so we will most likely be circling between ISO building and testing for a while.

**Comment by Tjzabel** [comment]
### Further Update
Build has been tested! At this time, everything seems to be working well, *except* for the dash to dock package, which doesn't seem to be installing correctly. 
I still need to discuss with others as to whether or not this should block on the beta release or not.

**Comment by Tjzabel** [comment]
Closing due to skipping F29.
