### ISSUE TITLE
Consider moving to GitLab for future development

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#151]
# What this is
At this point in TigerOS's development, we have come to a standstill. Previously, we have discussed moving to GitLab CI to handle all of our CI/CD needs. Personally, I still believe this is this best method forward. It would be great to move to a fully open-source solution for git hosting.

# Pros
* Some of the best CI/CD currently
* Better fine-tuning with a hosted git solution
* Ability to own our gitlab runners

# Cons
* Less project visibility
* Lose standing of being fully under RITlug domain

**Comment by Tjzabel** [comment]
It is also worth noting that, should we move to GitLab, we have the ability to mirror to GitHub, which would eliminate the project visibility aspect.

**Comment by nlMeminger** [comment]
If you could map out how the move would work and how we would maintain the mirror on GitHub, I would be on board with this idea.

**Comment by Tjzabel** [comment]
@nlMeminger Of course.

At the moment, it actually looks like we may be moving to Gitlab.com proper, instead of our hosted git.ritlug.com instance. 

I'm still thinking of the pure pros/cons against putting TigerOS on our hosted instance, but nonetheless, I will be putting together a gameplan on what a move would look like.

**Comment by nlMeminger** [comment]
Why would we move to gitlab proper instead of our instance?

**Comment by Tjzabel** [comment]
We can discuss that later.

**Comment by Tjzabel** [comment]
Moving to git.ritlug.com !
