### ISSUE TITLE
Create TeleIRC Bridge for Telegram and IRC

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#154]
This issue isn't directly related to our GitLab migration, but is something that I would like to do at the same time as our move. 

Creating an effective communication platform where the TigerOS developers and community can communicate to each other is very important to us moving forward. So, I would like to create:

1. Telegram TigerOS group
2. TeleIRC bot for Telegram <=> IRC

**Comment by nlMeminger** [comment]
We now have a telegram group called TigerOS

**Comment by Tjzabel** [comment]
Done!
