### ISSUE TITLE
About the current stage of development

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [RITlug/TigerOS#157]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [ ] Other issue
    * [x] Question 
* **Describe the issue / feature in 1-2 sentences**: 

Is it in active development or has it been discontinued?

**Comment by Tjzabel** [comment]
TigerOS is not currently in active development as of a year or so ago. Small contributions happen every once in a while, but for the moment this project is not actively being worked on.
