### ISSUE TITLE
What should our custom bookmarks be?

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#17]
I am thinking we should include the RITFOSS and RITLUG stuff and rit.edu. What else should we add?

**Comment by Tjzabel** [comment]
Maybe MyCourses is also another good one to add? And I love the idea of adding the RITFOSS and RITLUG bookmarks; however, I don't want the average student using this distrobution to be overloaded with FOSS bookmarks. What are your thoughts on that?

**Comment by axk4545** [comment]
@Tjzabel True. I was thinking I would add a FOSS@MAGIC page of @ritjoe's choosing and the RITLUG homepage or this repo and then maybe a link to a web irc client to connect to #ritlug

**Comment by axk4545** [comment]
@RITlug/rit-linux-team  thoughts?

**Comment by ReginaTL** [comment]
We should add TigerCenter and maybe RIT's dining website, I used it a lot bc I could never remember when Gracie's closed and now I use it to see what's open on campus at any given time.

**Comment by axk4545** [comment]
@RITlug/rit-linux-team closing if there are no objections
Here is the current list. rename to .html to view in a browser
[default-bookmarks.txt](https://github.com/RITlug/TigerOS/files/870424/default-bookmarks.txt)
