### ISSUE TITLE
Wifi connection script and connection during install

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#18]
Given that the RIT wireless network connection is generated by the connect-rit script on a completed install, how do we want to manage wifi during the install? should we have instructions on the wiki or should we use the script and just copy the config file to the new system after the install or something else? @RITlug/rit-linux-team

**Comment by Tjzabel** [comment]
@axk4545 It would be a good idea to simply have instructions on the wiki for this. Since Fedora has a GUI, it is quite simple to connect to the RIT network after the installation. In my opinion it would be best to leave it to the user to do this. Thoughts?

**Comment by axk4545** [comment]
@Josh1147582 think you could write up a blurb for the wiki?

**Comment by Tjzabel** [comment]
@axk4545 Have we decided how we are handling this issue? If so, is this able to be closed?

**Comment by Josh1147582** [comment]
Yeah, I can add instructions to the wiki. I'll go through it myself and write out instructions in the next couple days.

**Comment by axk4545** [comment]
@Josh1147582 think you could work on this after finals?

**Comment by Josh1147582** [comment]
Yeah, I'll have time Thursday night, hopefully. 
Sorry about the wait. I still can't pinpoint the GUI laptop issues. Maybe I'm using it wrong, and I need a writeup, lol.

**Comment by Tjzabel** [comment]
This is definitely still an issue after installing the latest TigerOS on a fresh machine with cinnamon.

**Comment by ct-martin** [comment]
Working on testing, also related to #41

**Comment by linux-modder** [comment]
```
HWADDR={HW_ADDR}
ESSID={RIT_WIFI_AP}
MODE=Managed
MAC_ADDRESS_RANDOMIZATION=default
TYPE=Wireless
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=dhcp
DEFROUTE=yes
IPV4_FAILURE_FATAL=yes
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
IPV6_ADDR_GEN_MODE=stable-privacy
NAME=TIGER_WIFI
UUID={UUID}
ONBOOT=yes
USERS={LOCAL_USERNAME}
```

Above is a template that I sanitized from the local EDU connect on my laptop this could be a skeleton ifup script for RIT.

**Comment by axk4545** [comment]
@Josh1147582 Please add tutorial when you can as actioned at last meeting.

**Comment by axk4545** [comment]
Replaced with documentation.
