### ISSUE TITLE
Custom branding

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#19]
Custom branding and wallpapers. Branding should be implemented as an RPM package per #12

**Comment by axk4545** [comment]
Next steps to be complete when possible:
Move branding and wallpapers to packages.
wallpapers package is at http://mirrors.rit.edu/fedora/fedora/linux/releases/25/Everything/source/tree/Packages/d/desktop-backgrounds-25.0.0-1.fc25.src.rpm

**Comment by axk4545** [comment]
@ReginaTL for setting theme and other cinnamon prefs see  https://superuser.com/questions/1006983/how-to-set-cinnamon-preferences-in-command-line/1087459

**Comment by ReginaTL** [comment]
Ok so Cinnamon has themes. Basically I'm going to try to create our own Cinnamon/GTK theme (by playing with the conf files) and then have that be the default look for the Cinnamon desktop.

**Comment by axk4545** [comment]
@ReginaTL I figured out how to set the default theme! :) Basically put the below code in the `%post` section of our kickstart before the line  `cat >> /etc/rc.d/init.d/livesys << EOF`.
I can help when we get to that stage since I know the kickstart structure.
You can find the values and paths for the settings in dconf-editor after you set things the way they should be.

` create gschema override to set cinnamon gtk-theme
-
-cat > /usr/share/glib-2.0/schemas/cinnamon-live.gschema.override <<EOF
-[org.cinnamon.desktop.interface]
-gtk-theme='our theme'
-[org.blah.blah]
-field='value'
-EOF
-
-glib-compile-schemas /usr/share/glib-2.0/schemas/
-`

**Comment by axk4545** [comment]
@ReginaTL closing. please open a new issue for remaining tasks.
