### ISSUE TITLE
Scripts to uninstall packages based on major

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#22]
Using this [post install script](https://github.com/RITlug/TigerOS/blob/devel/scripts/postinstall) as a base create a script to revert each of the changes made in each case statement. eg rm files that were manually copied, dnf remove packages, clean up or backup configs. Let me know in Telegram or IRC if you have questions.

**Comment by axk4545** [comment]
I would recommend adding autoremove statements after each remove  so that the deps get cleaned up too. Definitely test this before pushing it as it is potentially destructive. RE the port it seems you could revert it by changing -a to -d  according to https://fedoraproject.org/wiki/SELinux/semanage but I would confirm on #fedora on irc.freenode.net I can do that if needed. let me know if you have questions.

**Comment by axk4545** [comment]
@Tjzabel I think that we are ready to add a couple more things from the CS group. ok if I leave it to you?

**Comment by Tjzabel** [comment]
@axk4545 Yep, I'll let you know if I need anything.

**Comment by axk4545** [comment]
@Tjzabel please close if we are good
