### ISSUE TITLE
Bookmarks not being applied from package

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#27]
tigeros-bookmarks package is being installed during build but the bookmarks are not present in the installed copy of Firefox. I have cleared the firefox data and reinstalled the bookamrks package and the issue still persists. any ideas?

**Comment by axk4545** [comment]
fixed file name

**Comment by axk4545** [comment]
Apparently Firefox bookmarks are pulled in a t build time according to [here](https://bugzilla.redhat.com/show_bug.cgi?id=1338010). Since we do not have the resources to rebuild and maintain Firefox, I am going to implement a temporary fix until this feature is added to upstream.

**Comment by axk4545** [comment]
Maybe one of us could try to add a patch to firefox to allow bookmarks to be added at runtime as suggested in the bugzilla.

**Comment by Tjzabel** [comment]
@axk4545 where are we on this issue?

**Comment by axk4545** [comment]
@Tjzabel I believe we have it so that the firefox homepage is set to an HTNL file with a list of bookmarks. I would like to see if we can add the actual bookmarks though.

**Comment by axk4545** [comment]
Temporary fix implememented by [this commit](https://github.com/RITlug/TigerOS/commit/12d293136c6f0689c2162c2d6576970a3e021556) Still an issue in upstream
