### ISSUE TITLE
Autostart postinstall and enablerpmfusion on first login to new system

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#28]
Currently there is code in [the ks](https://raw.githubusercontent.com/RITlug/TigerOS/devel/tigeros.ks) that should trigger postinstall to run on first login. This is still being debugged and could be improved. We also need to work out how we want to trigger the enablerpmfusion script (maybe in postinstall before the case statement?)
@Tjzabel @Josh1147582 any help is appreciated.

**Comment by Tjzabel** [comment]
@axk4545 I will try to look at this issue when I get the chance.

**Comment by axk4545** [comment]
@Tjzabel ok. FYI I am working on the scripts atm. watch Telegram for the commit message

**Comment by Tjzabel** [comment]
@axk4545 yeah sure. I won't be available to do any work until a little after 4 anyways

**Comment by axk4545** [comment]
@Tjzabel added enablerpmfusion to top of postinstall

**Comment by Tjzabel** [comment]
@axk4545 I believe we solved this issue. Closing.

**Comment by axk4545** [comment]
The script runs but immediately closes the terminal window after entering the password

**Comment by Tjzabel** [comment]
@axk4545 where is the file put? Ran fine for me when placed in .config/autostart/

**Comment by axk4545** [comment]
@Tjzabel ~/.config/autostart/tigeros-postinstall.desktop. if run manually it works fine @linux-modder any ideas?

**Comment by Tjzabel** [comment]
@axk4545 I was able to have it run on a fresh fedora install. I threw the file in that location, rebooted the VM, and it worked just fine. 

Are you able to reproduce your issue with it closing after entering the password?

**Comment by axk4545** [comment]
@Tjzabel Yes. I am running the latest TigerOS iso from tigeros.ritlug.com/isos in a VirtualBox VM.

**Comment by linux-modder** [comment]
as of 0513 iso still requires explicit invocation while perms are as shown:

[tigers@tigers ~]$ ls -la /usr/local/bin/postinstall 
-rwxr-xr-x. 1 root root 4589 May 13 05:01 /usr/local/bin/postinstall

this is on a raw metal fedora 25 (415Gb) / (30Gb) tigeros install:

**Comment by axk4545** [comment]
@linux-modder thank you it would seem we need to possibly fix the permissions on the script itself. @johnraff @2ion I would be interested in how you have decided to implement the autostarting of the Bunsen Labs postinstall script.

**Comment by johnraff** [comment]
> autostarting of the Bunsen Labs postinstall script

There are two:
1) A script to set up the default user configuration during the first login, this is triggered from a lightdm config fragment: https://github.com/BunsenLabs/bunsen-configs/blob/master/50_bunsen.conf
2) A script to offer the user various installation options etc, run after login from ~/.config/openbox/autostart: https://github.com/BunsenLabs/bunsen-configs/blob/master/skel/.config/openbox/autostart 

Each of these scripts places a marker file in ~/.config/bunsen, and exits immediately if that file is already present.

**Comment by axk4545** [comment]
> A script to set up the default user configuration during the first login, this is triggered from a lightdm config fragment: https://github.com/BunsenLabs/bunsen-configs/blob/master/50_bunsen.conf
@johnraff is this something that the user sees or could interact with? Right now we have [this desktop file](https://github.com/RITlug/TigerOS/blob/devel/scripts/tigeros-postinstall.desktop) and the script either fails to run or closes after the password prompt

**Comment by johnraff** [comment]
No, */usr/lib/bunsen/configs/bl-user-setup* is run by lightdm, as root, *before* the user is logged in.

**Comment by axk4545** [comment]
@axk4545 @me I got it set Terminal=false also play with profile arg to see if it matters

**Comment by axk4545** [comment]
Well now it seems to work too well... it runs on the livecd.

**Comment by axk4545** [comment]
I think I have a workaround in removing the desktop file from the liveuser's autostart in %post of the kickstart. will implement in builds once I have tested and received feedback on other changes.

**Comment by ctm2142** [comment]
Other ideas:
- Check if running from the livecd disk (Main disk is labeled "TigerOS-live")
- Look at using a service like PiBakery does ([https://github.com/davidferguson/pibakery-raspbian](https://github.com/davidferguson/pibakery-raspbian))

**Comment by linux-modder** [comment]
I assume you mean this: https://github.com/davidferguson/pibakery-raspbian/blob/master/etc/systemd/system/pibakery.service? If so that would work indeed.

**Comment by Tjzabel** [comment]
Sooo it seems this isn't an issue. It may possibly be an issue running TigerOS in a VM, but using the LiveCD on an actual machine does not seem to trigger the PostInstall prematurely as stated.

**Comment by axk4545** [comment]
@Tjzabel thanks for checking on this. I would like to get a couple more confirmations that this isn't an issue before I close.

**Comment by ct-martin** [comment]
To be retested after #41

**Comment by axk4545** [comment]
I approve of the last comment

**Comment by ct-martin** [comment]
There was a question as to the legality/liability of providing rpmfusion, namely the same reasons Fedora doesn't may affect us. For discussion at meeting, just putting in issue. (cc @axk4545 )

**Comment by Tjzabel** [comment]
Anyone have any further information on this topic? I have tried this quite a few times, and it works as advertised. However, I have only tested on one machine. Has anyone else been able to test this on their own hardware?

**Comment by axk4545** [comment]
@Tjzabel I can test on my TigerOS  install. It does seem to be functioning. We can merge this with the GTK UI issue #55 unless it comes back up
