### ISSUE TITLE
removal is throwing errors on missing packages

### ISSUE THREAD

**Issue by linux-modder** [RITlug/TigerOS#33]
adding --ignore-missing to the removal script at least on lines 69 and 84

**Comment by Tjzabel** [comment]
@linux-modder Can you replicate this issue? I have tried replicating with a fresh Fedora VM, and have not gotten any errors. Currently testing for issues with line 84. Line 69 I could not replicate.

**Comment by Tjzabel** [comment]
Added --ignore-missing tag. Closing issue.
