### ISSUE TITLE
Spin and Alloy scripts are called but never installed

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#34]
#### Current location set for spin.sh:
    /usr/local/bin/se/spin.sh

#### Current location set for alloy.sh:
    /usr/bin/tigeros/se/alloy.sh

**Comment by axk4545** [comment]
The files are actually installed from the tigeros-scripts package. I am looking through the source atm to try to find the issue.

**Comment by axk4545** [comment]
fixed
