### ISSUE TITLE
Wallpaper not in right category in chooser

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#35]
This may just be a syntax issue with gsettings. I will look into it.

**Comment by linux-modder** [comment]
The Wallpapers are set now, can select in the Backgrounds section as the second 'Backgrounds'  option, but none of the 3 options are auto setting themselves on first run. ( tested on 0513.iso)

**Comment by axk4545** [comment]
@linux-modder I found https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Desktop_Migration_and_Administration_Guide/custom-default-values-system-settings.html I am thinking we put that file in the backgrounds package. Thoughts?

**Comment by linux-modder** [comment]
yes but you did not append or override the default one you added a second one which I would recommend for future releases labeling TigerOS or similar to distinguish them from the Fedora default ones assuming someone wishes to revert to stock backgrounds or later add a custom user-specified additional wallpaper.

**Comment by axk4545** [comment]
@linux-modder will see if I can find the name of it.

**Comment by axk4545** [comment]
ask in #fedora-design on freenode about naming wallpaper collections. will update with response.

**Comment by axk4545** [comment]
see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Desktop_Migration_and_Administration_Guide/customize-desktop-backgrounds.html
Hope to have a fix in devel as soon as I hear back from @ReginaTL  about the picture aspect setting

**Comment by axk4545** [comment]
Better idea: https://github.com/kororaproject/kp-korora-settings-gnome/blob/master/upstream/org.korora.gschema.override#L156

**Comment by axk4545** [comment]
Fixed in 20170531 iso and in devel branch. Still need to check categories

**Comment by ct-martin** [comment]
To be retested after #41

**Comment by axk4545** [comment]
I believe @Tjzabel was actioned for this

**Comment by Tjzabel** [comment]
In order to fix this issue, wallpapers need to be installed to `/usr/share/backgrounds/gnome/` from [this](https://github.com/RITlug/TigerOS/blob/devel/sources/tigeros-backgrounds/tigeros-backgrounds.spec) spec file. Currently this file does not install our wallpapers to this location.

**Comment by Tjzabel** [comment]
Since we have just created a new ISO, I would like to confirm the correct path

**Comment by Tjzabel** [comment]
This issue has been tested. Closing.
