### ISSUE TITLE
pycharm is not pulling itself in ( COPR issue)

### ISSUE THREAD

**Issue by linux-modder** [RITlug/TigerOS#36]
on the postinstall run (which still needs a explicit invocation on 0513), you see:

Error: This repository does not have any builds yet so you cannot enable it now.
Last metadata expiration check: 0:02:17 ago on Sun May 14 00:32:46 2017.
No package pycharm-community available.
Error: Unable to find a match.

reason stems from the repo presently being a metadata only repo as evidenced with the repo file contents: proof highlighted by >>> <<<

[phracek-PyCharm]
name=Copr repo for PyCharm owned by phracek
baseurl=https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/fedora-$releasever-$basearch/
>>> type=rpm-md <<<
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1

this is due to soem recent dist-git/copr outages/failures NOTHING to do with the script itself. 

as a temporary workaround point the script at:
https://copr-be.cloud.fedoraproject.org/results/phracek/PyCharm/fedora-25-x86_64/00549395-pycharm-community/pycharm-community-2017.1.2-1.fc25.x86_64.rpm

and optionally the -doc /  -plugins rpms in the same directory.

**Comment by axk4545** [comment]
Temp fix in place. Leaving open as a reminder to revert later.

**Comment by axk4545** [comment]
@linux-modder do we know if this has been fixed upstream?

**Comment by linux-modder** [comment]
The repo data has not changed it seems still indicates rpm-metadata  however might be a way to setup a monitor of his builds to point to the latest successful build (at present one from 2 weeks ago, however his cycle of builds does _APPEAR_ to be every two weeks from the history)

**Comment by axk4545** [comment]
Still an issue and possibly a blocker for full move to F26 @linux-modder @Tjzabel

**Comment by linux-modder** [comment]
@axk4545 @Tjzabel I will look again, sorry I've been sidelined with other projects recently sorry.

**Comment by Tjzabel** [comment]
@axk4545 why are we installing PyCharm this way, instead of installing it as we have for IntelliJ IDEA?

**Comment by axk4545** [comment]
COPR is easier than the manual scripted install. We can discuss Friday
though

Aidan Kahrs
abkahrs@gmail.com

**Comment by linux-modder** [comment]
@Tjzabel PyCharm-community which is what is in play for TigerOS is not at the version needed/desired when pulled from IntelliJ  IDEA

**Comment by Tjzabel** [comment]
@linux-modder Well, if the Copr still isn't available I can always make a script, even if temporary, to install the pycharm community edition if it's holding us back.

**Comment by axk4545** [comment]
@Tjzabel @Tjzabel21 Just saw the comment. We can talk at the meeting. The short answer is it is better to pull from COPR since that is an RPM rather than add it to our collection of scripts and then have to maintain it.

**Comment by axk4545** [comment]
@linux-modder I think this is fixed now with F26. Mind verifying?

**Comment by axk4545** [comment]
Just tested against the COPR on Fedora 26 and it succeeded and can launch
