### ISSUE TITLE
TigerOS in RIT labs

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#42]
Opening for tracking purposes. Primary contact is James Craig. 
jmc AT cs DOT rit DOT edu
Manager of Technical Services
585.475.5254
GOL-3599

**Comment by ct-martin** [comment]
List of packages on Glados: https://paste.fedoraproject.org/paste/IQczZj-4UKdJjXWeph13ZA
Note: password protected. Project members can get it from me or Aidan, others, sorry but we can't give it to you (security concerns)

**Comment by ct-martin** [comment]
Made title more general since after talking to SJ during FOSS Hours, there is a POSSIBILITY (NOT guaranteed) that we MIGHT be able to get TigerOS onto the new MAGIC computers.

**Comment by ct-martin** [comment]
This issue is blocked until we have a working final release. This issue will be looked again as we approach said release

**Comment by ct-martin** [comment]
Not happening in the foreseeable future, or at least this academic year
