### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#43]
Looking for opinions. Will crop out black border & get at a better resolution in the final versions.

![desktop](https://user-images.githubusercontent.com/25327135/30413403-db80552c-98eb-11e7-9ec9-83b21924ad59.PNG)
![randomapps](https://user-images.githubusercontent.com/25327135/30413404-db8644f0-98eb-11e7-9bc7-d514b29ac78d.PNG)
![startmenu](https://user-images.githubusercontent.com/25327135/30413405-db874440-98eb-11e7-9003-234472df637d.PNG)
![updater](https://user-images.githubusercontent.com/25327135/30413406-db879968-98eb-11e7-983a-8cef4b8b1528.PNG)

**Comment by linux-modder** [comment]
I'd add things like Pycharm and other Major -centric Apps running, and migrate to a PR even.

**Comment by axk4545** [comment]
@ct-martin I second @linux-modder as well as saying we should switch the terminal one so it isn't running as root as that is bad practice that we don't want to spread.

**Comment by Tjzabel** [comment]
@ct-martin yess, this looks really good.

**Comment by ct-martin** [comment]
#44 Need updates to get one of dnfdragora, but got a couple of hexchat instead for now. All are 1080p

**Comment by linux-modder** [comment]
Recommendation for apps to showcase in the screenshots: 
- A few/the most important ones from each major/discipline
- desktop selection options menu -- so folks can see that if they wish to change the background or do different resolutions.etc they can 
- show root as being sudo'd into or sudo su / su -c ' {command_string} '

**Comment by axk4545** [comment]
@ct-martin I provisonally merged your PR. what updates are needed for dnf-dragora? also please consider doing some of the things @linux-modder suggested particularly the first one.

**Comment by ct-martin** [comment]
I need Fedora updates to show that it does updates (my system was already up to date). I will get some of PyCharm, etc however, the script was not working and I decided I wasn't messing with repos for the moment

**Comment by linux-modder** [comment]
@ct-martin while I might be misunderstanding your last comment but if you pulled this on 0910 or within a day or two, seeing as it was built with all updates ( from the mirrors) on 0910 not much has updated since then.

@axk4545  wrt dnf-dragora, is the follow of the gnome-version of dnf-yumex or whatever the gui tool was called for dnf/yum it is a new thing to 26, and worthy of a mention in release notes and screenshot. ( latter appears to exist already.)

**Comment by ct-martin** [comment]
@linux-modder @linux-modder What I meant was that I had an already up-to-date system so I felt it was not worth getting a dnfdragora screenshot yet.

**Comment by Tjzabel** [comment]
Where are we with these screenshots now

**Comment by ct-martin** [comment]
@Tjzabel See /screenshots, we have a number.

**Comment by Tjzabel** [comment]
@ct-martin yeah I see we have a decent amount now. I'm simply wondering where we are with this issue after the current screenshots we have.

**Comment by ct-martin** [comment]
@Tjzabel I needed updates to show a dnfdragora update (probably can do now that it's been a week or so). Also, with the GNOME discussion I'm not really focusing too much on it.

**Comment by Tjzabel** [comment]
@ct-martin makes sense. I'll keep this issue up then.

**Comment by ct-martin** [comment]
Also dependent on outcome of #41

**Comment by ct-martin** [comment]
Waiting on implementation of Dash to Dock

**Comment by axk4545** [comment]
@ct-martin Dash to dock in repo now

**Comment by Tjzabel** [comment]
Moving this issue over to #103
