### ISSUE TITLE
Change lock screen when no user selected to be the TigerOS default

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#45]
The lock screen is still using the default Fedora one on the LiveCD, we should change it to the TigerOS one if we can

**Comment by axk4545** [comment]
@ct-martin what do you mean? AFAIK we don't have a TigerOS one.

**Comment by ct-martin** [comment]
So this also happens on the full install when no user is logged in
![fixme2](https://user-images.githubusercontent.com/25327135/30514528-5cbdd8c2-9ae4-11e7-9089-312402874918.png)

**Comment by Tjzabel** [comment]
@ct-martin This is a pretty easy fix. You can change out the default wallpaper with ah TigerOS-themed one. Backgrounds are found in `usr/share/backgrounds`

**Comment by ct-martin** [comment]
@Tjzabel This is a suggestion to change default behavior

**Comment by Tjzabel** [comment]
@ct-martin Understood. Again, I am simply pointing out the solution :P

**Comment by axk4545** [comment]
This is kinda dependent on our DE. If we go to GNOME this becomes moot as GNOME uses GDM as opposed to lightdm. We will deal with this at the first official meeting on Oct 6th.

**Comment by axk4545** [comment]
@Tjzabel please investigate if this is possible in gnome and if you can make it a spec and sources.

**Comment by axk4545** [comment]
manually set for public demos until tweak implemented

**Comment by axk4545** [comment]
@Tjzabel low priority but adding a comment so we know next steps. 

We need to find the config file for GDM and make a patchfile that we can add to the UI tweaks package to point at the new lockscreen image. the path to the image can be found in the backgrounds package but should be `/usr/share/backgrounds/tigeros` or a subdir of that.

**Comment by Tjzabel** [comment]
## Update

Screensaver has been implemented to be [Wallpaper 2](https://raw.githubusercontent.com/RITlug/tigeros-backgrounds/master/tigeros-backgrounds-1.0/wallpapers/wallpaper2-1920x1080.jpg), which is currently also the default background image. 

I have added a lot of content in regards to the TigerOS UI, so I am going to put this issue on hold until we _know_ the fix is working.

**Comment by Tjzabel** [comment]
Fix definitely works. Let me know if this is the image you would like to use:
![Lockscreen](https://imgur.com/pyzU0QA)

**Comment by ct-martin** [comment]
@gen1e can we try to make something that doesn't overlap with the text as much?

**Comment by Tjzabel** [comment]
@ct-martin this was my same thought. I am thinking of maybe having just the orange background without the TigerOS logo there? That way the text is visible, and when you log in the logo pops back up.

**Comment by gen1e** [comment]
Some options, though I have thought about maybe designing a completely new lockscreen wallpaper. I've also been working out if I can get a mid wave Tiguin as an alternative for the left and right versions.

![lockscreen1_1-1920x1080](https://user-images.githubusercontent.com/15071353/42424607-9fdead42-82d4-11e8-87df-878d97e6e697.png)
![lockscreen1_2-1920x1080](https://user-images.githubusercontent.com/15071353/42424608-9fef1b14-82d4-11e8-8fe1-dd3c0ee17fba.png)
![lockscreen1_3-1920x1080](https://user-images.githubusercontent.com/15071353/42424609-9ffe43d2-82d4-11e8-819b-1af2ce05670b.png)
![lockscreen3_1-dark-1920x1080](https://user-images.githubusercontent.com/15071353/42424610-a00faf3c-82d4-11e8-94d1-9e65e1a3a59d.png)
![lockscreen3_2-dark-1920x1080](https://user-images.githubusercontent.com/15071353/42424611-a02233f0-82d4-11e8-92e5-0399a77f836a.png)
![lockscreen3_3-dark-1920x1080](https://user-images.githubusercontent.com/15071353/42424612-a032c422-82d4-11e8-9d5d-7388c988a454.png)

**Comment by ct-martin** [comment]
@Tjzabel can you try to get these as screenshots on a VM lock screen? I think it'd be much easier to decide if we had a live sample

**Comment by Tjzabel** [comment]
I like how the first version looks!

### Light
![updated-screensaver](https://user-images.githubusercontent.com/22552344/42425175-f77d21c0-82e6-11e8-937a-1d4f06b90a98.png)

### Dark
![updated-dark](https://user-images.githubusercontent.com/22552344/42425194-5033f348-82e7-11e8-8627-18eef28cb883.png)

**Comment by ct-martin** [comment]
I like the first one as well. @Tjzabel - could you do the orange ones with
the tiguin "just because" so we can see?

**Comment by Tjzabel** [comment]
## Orange Tiguin Lockscreen
![orange_right](https://user-images.githubusercontent.com/22552344/43359996-ac519da8-927b-11e8-991f-99ea7f7237fe.png)

## Dark Tiguin Lockscreen
![dark_left](https://user-images.githubusercontent.com/22552344/43360007-bf9c7e64-927b-11e8-985e-b0f05a9fd0ae.png)

**Comment by gen1e** [comment]
Yea I would definitely just keep the Tiguin out of it, not thrilled how either looks, it just looks weird to me. The other two without the Tiguin look great tho.

**Comment by Tjzabel** [comment]
Completed!
