### ISSUE TITLE
Lock screen time is non-US

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#46]
![Lock screen time by default is in Military Time](https://user-images.githubusercontent.com/25327135/30514401-0f6bb7c6-9ae2-11e7-80e7-6c31a799ba14.PNG)

**Comment by Tjzabel** [comment]
You are using Gnome, correct? 

In order to change the default time from 24h to 12h with the gnome-clock-applet you run the command: 
`gsettings set org.gnome.desktop.interface clock-format 12h`

**Comment by ct-martin** [comment]
@Tjzabel Point is should be 12hr by default. Also, this is on Cinnamon, so sort of

**Comment by Tjzabel** [comment]
@ct-martin Understood. We can run this command at startup or add it to the ks to make it start in 12h time format.

**Comment by axk4545** [comment]
@ct-martin @ctmartin @Tjzabel it's all good. I know what to do to fix it just haven't had time. it is in the lightdm-gtk-greeter.conf file. I would like to maybe make this part of a UI tweaks package.

**Comment by axk4545** [comment]
see #45

**Comment by Tjzabel** [comment]
From what I've noticed going through the TigerOS install, there is an option to change the time format in the Anaconda installer.

**Comment by ct-martin** [comment]
Verified as still appearing in the GNOME builds

**Comment by axk4545** [comment]
Please see if this can be done in a package with the lockscreen since they are related

**Comment by axk4545** [comment]
manually set for public demos  until implement tweak

**Comment by axk4545** [comment]
@Tjzabel adding notes on next steps here as well. Again, this is low priority but I want the notes so we can come back to it. 
We should add a gschema  override like we did for the wallpaper to set the key. This will be part of our UI tweaks package.

**Comment by Tjzabel** [comment]
Command to change clock to 12h:

`gsettings set org.gnome.desktop.interface clock-format 12h`

**Comment by Tjzabel** [comment]
Current status on this issue: Commit has been added and is now set for testing.

If testing completes, and works without error, I will be closing this issue. If not, I will update this comment with the errors.

**Comment by Tjzabel** [comment]
Tested and fixed.
