### ISSUE TITLE
Replace post install script with GTK UI or metapackage in software selection

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#55]
@ct-martin @Tjzabel @Josh1147582

**Comment by ct-martin** [comment]
For ref in case we go the route of a custom comps.xml file: [https://github.com/manatools/dnfdragora/blob/master/tools/gen-comps-category-list.sh](https://github.com/manatools/dnfdragora/blob/master/tools/gen-comps-category-list.sh)

**Comment by ct-martin** [comment]
@axk4545 @jflory @Tjzabel21 @josh1147582
While some of this will end up in another issue, this is where the process/discussion is happening right now, so forwarding this from Aidan to here (see below). I think we should discuss Week 8 and then Week 9 we should make a milestone for this and then break into issues based on the discussions and subsequent research.
```
1. Keep our "script-based" RPMs out of the iso, namely the major-specific ones. If we keep them just in a repository that TigerOS can grab from through dnf install, it'll be less we have to build each time. Also, not every user will need them. Ideally, our "first run" script would just be a bunch of `dnf install`s.
2. Add metapackages to our repo: packages that point to other packages. So installing the "CS" metapackage would install all the tools that a CS student might need.
```

**Comment by Tjzabel** [comment]
I have a base design for the UI completed. However, this will not be able to be finished by this Saturday for the Maker Faire. I may remove this issue from the milestone. Thoughts?

**Comment by ct-martin** [comment]
I think you should keep working on it (as time permits) and on Friday we
can decide. Depending on how far it gets we could leave it on there as a
"for people who are really interested" thing. Pinging @axk4545 @jflory7
since they have more experience in this kind of stuff.


--
Christian Martin

**Comment by Tjzabel** [comment]
@ct-martin @axk4545 @jflory7 I agree. I am going to be working on this until completion, but we won't be able to get a model ready for the Maker Faire. 

We are going to need to set up a model on how to incorporate the code of the GUI into this repository. There are dependencies needed, and so I'm trying to figure out the best way to set this up so if others want to contribute, they are able to pull the code, and compile/test on their own machine.

**Comment by axk4545** [comment]
Sounds good. If we can have a window with the elements as an example of the
UI  for Saturday that would be cool.

Aidan Kahrs
abkahrs@gmail.com

**Comment by Tjzabel** [comment]
After the meeting today, we have decided not to include the GTK UI in the Maker Faire. Tentative release for a fully working product is during winter break.

Current progress: ironing out the design layout. I also need to figure out the best way to include the GTK UI within the tigeros repository.

Current thought process:
1. Create design layout
2. Implement design
3. Add functionality
4. Merge final binary into tigeros project

Thoughts?

**Comment by jflory7** [comment]
_Discussed in our [weekly meeting](https://github.com/RITlug/TigerOS/wiki/Next-meeting-agenda)._

## GTK implementation for repo

* Will we have other sources?
* What package name to use? (`tigeros-setup-wizard`, `tigeros-software-selection`, etc.)
* Do we want to make it more than a manager and tie all of our customizations to a single package with sane defaults? Or the meta-package approach?

The initial steps are to create the implementation first. There are concerns about GTK being more complicated than anticipated. We may focus more on GNOME-specific changes. We'll revisit this sometime after break, and @Tjzabel will add new announcements to the next meeting agenda on any progress.

**Comment by ct-martin** [comment]
Correction: The `tigeros-manager` name suggestion was because currently the
UI only is for doing package installation, but we want to at least leave
open the option to do other things later (for example, allowing a user to
install defaults for programs that might be closer to what they're coming
from) in order to help further our end goal of making Linux easier for RIT
Students, particularly new users. By naming the package
`tigeros-software-selection` we are
semantically/canonically/whatever-for-naming restricting the package's
usage to that specific functionality. This suggestion will affect nothing
with the metapackages, nor will it change where our currently proposed
modifications are being done.


--
Christian Martin

**Comment by ct-martin** [comment]
UX suggestion from kinri: show commands as they are being executed

**Comment by axk4545** [comment]
Reference metapackage: https://src.fedoraproject.org/rpms/qt5/blob/master/f/qt5.spec

**Comment by axk4545** [comment]
[comps.txt](https://github.com/RITlug/TigerOS/files/1790860/comps.txt)
How do do comps in more detail

**Comment by Tjzabel** [comment]
## Update
The repo to house the code for the software manager will live [here](https://github.com/RITlug/tigeros-software-manager)

**Comment by Tjzabel** [comment]
Closing as not being worked on now. Current goal is integrating with GNOME Software. If this is not possible, I would like to look at adding a patch to allow the capability before we fully decide to go off on our own.
