### ISSUE TITLE
Create dark theme TigerOS background

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#57]
Black and dark grey @ct-martin @ReginaTL whoever wants it... (low priority)

**Comment by Tjzabel** [comment]
@axk4545 I can also help with the icon theming to create a dark theme if someone wants to do a dark wallpaper.

**Comment by ReginaTL** [comment]
Wallpapers! Of course other people are more than welcome to come up with stuff but I made two so far that I like. Personally I prefer the greyscale penguin one but please let me know what you guys think of them.
![wallpaper2-dark](https://user-images.githubusercontent.com/15071353/32523228-603fc5f0-c3e8-11e7-98b3-e01ac3f74c22.png)
![wallpaper3-dark](https://user-images.githubusercontent.com/15071353/32523229-60496bfa-c3e8-11e7-8406-2e2ad3e63bac.png)

**Comment by ct-martin** [comment]
@ReginaTL Not a fan of the mottled greyscale one, the plain grey one is amazing though. There is an issue with at least one of them not being horizontally centered, but otherwise looks good

**Comment by axk4545** [comment]
👍 to that second one. @ReginaTL can you PR these in or otherwise add them to the repo and let me know when they are there so I can change the backgrounds package as needed? or you can rebuild it if you want.

**Comment by axk4545** [comment]
@ReginaTL please PR these changes in or otherwise get them to me so they can be integrated in to.

**Comment by axk4545** [comment]
Going to close as changes were merged.
