### ISSUE TITLE
Package dash to dock

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#59]
We can pull upstream releases from [here](https://github.com/micheleg/dash-to-dock/releases) and write a spec like [this](https://github.com/kororaproject/kp-gnome-shell-extension-workspaces-to-dock/blob/master/build/gnome-shell-extension-workspaces-to-dock.spec)

**Comment by axk4545** [comment]
need to discuss source organization with @ct-martin and how that works with build automation

**Comment by axk4545** [comment]
@ct-martin did we decide how to handle the source for this? if we don't host it we can do a `spectool -g` on the spec file to grab the source by URL.

**Comment by ct-martin** [comment]
@axk4545 ???
If you mean for the dash-to-dock source, grabbing the tar.gz from the release like we are now

**Comment by axk4545** [comment]
@ct-martin so grab with spectool -g or manually input URL?

**Comment by ct-martin** [comment]
Done.
