### ISSUE TITLE
Package .deb files

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#66]
Support greater user base (Debian+Ubuntu)
Part of CI in #29
Should not be a major time investment

**Comment by ct-martin** [comment]
Will all be Ansibled

**Comment by Tjzabel** [comment]
I'm almost wondering if we want to remove this issue entirely. I don't see this as something the TigerOS team will be doing at any point in the next year. If this is truly something we want to do, we can reopen this issue.

@ct-martin thoughts?

**Comment by ct-martin** [comment]
@Tjzabel there are a couple other long-term goals in issues, we should discuss what we want to do with them in the meeting in 20 minutes

**Comment by ct-martin** [comment]
For if we look at later on: https://openbuildservice.org/

**Comment by ct-martin** [comment]
Based on meeting, this isn't something we have bandwidth to consider as a possibility until after a final release and this issue is going to be closed.
