### ISSUE TITLE
Make Dash to Dock in UI tweaks

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#68]
We should either have Dash to Dock depended by a ui-tweaks package or similar (so gets added to builds, however, we decided that the repackaging should be pure and that config stuff for repackaged packages should be in another package, such as a ui-tweaks/similar).

**Comment by axk4545** [comment]
Added initial skeleton spec

**Comment by axk4545** [comment]
dependent on #57, #45 and #46 being completed of patches for them being added to the issues

**Comment by axk4545** [comment]
get dconf or gsettings keys for dash to dock and gnome tweaks for @ctmartin

**Comment by ct-martin** [comment]
As per discussion in meeting, the dash to dock settings in the file are the
global defaults, not for a specific user. I am proposing that we override
it to our defaults in the ui-tweaks package(-to-be).


--
Christian Martin

**Comment by jflory7** [comment]
_Discussed in our [weekly meeting](https://github.com/RITlug/TigerOS/wiki/Next-meeting-agenda)._

## Converting suggestions to code

@ct-martin has screenshots of some config settings for Dash to Dock that he liked. We need to convert the screenshots into scripts to configure Dash to Dock with our changes.

Some notes to consider:

* Need to discuss how to override default settings
* Package should be kept to upstream as much as possible
* TigerOS ui-tweaks package must go _after_ Dash to Dock install

## What's next

We need to get an implementation of the Dash to Dock settings and review it with the team. @ct-martin is working on this and has some screenshots he will upload to this ticket. He intends to work on it over break, and we will follow up at our first team meeting in January.

**Comment by ct-martin** [comment]
Correction: This is under @Tjzabel's GNOME action item.
Also, a slight detail thing, the ui-tweaks package must *make its changes*
after the dash-to-dock install, although this should be covered by the
dependency. Worst case we can do this with a bunch of `sed` commands,
however, we'd like a better solution than that, such as something to do
with dconf and/or gconf.


--
Christian Martin

**Comment by axk4545** [comment]
Well dconf or gsettings. gconf is deprecated

Aidan Kahrs
abkahrs@gmail.com

**Comment by KST123ABC** [comment]
dconf https://micheleg.github.io/dash-to-dock/download.html

**Comment by Tjzabel** [comment]
Issue update:
Currently we are trying to figure out how to create a new schema. When enabling dash-to-dock, a new dconf schema is created, and the appropriate key is appended to the end. It is proving to be a challenge to create a brand new schema, and then append the correct key.
