### ISSUE TITLE
Docs/New Site Fixes

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#72]
Putting in an issue until I get a chance to do them

- Fix order of JS scripts
- Make the header background a real image embed instead of CSS trickery
- Make Popper JS from a CDN

**Comment by jflory7** [comment]
@ct-martin I would suggest breaking this ticket into separate, smaller tickets. Doing this does two things:

1. Makes it easier for others to see tasks that need help (esp. if marking some as "easyfix" tasks)
2. Makes it easier to track and measure concrete progress

My rule of thumb for filing new tickets is to try to have a clear idea of what "done" looks like.
