### ISSUE TITLE
Publish TigerOS website by Nov. 18

### ISSUE THREAD

**Issue by jflory7** [RITlug/TigerOS#76]
# Summary

The TigerOS website needs to be hosted on the public web so we can point people at our project in time for Mini Maker Faire on Saturday, Nov. 18th.

# Background

@jrtechs helped create our website in #69. All background details for the website are found in that PR.

# Details

The website is a helpful resource to point people at in an exhibition hall, and also is a more "friendly" takeaway for a visitor than our GitHub repo. I want to get this hosted in time for the Maker Faire so we can point people at our project and to help us gain some momentum there.

I've assigned @Serubin to this issue to help with infrastructure concerns. Ideally, this should be run on Titan. I'm not sure what the preferred way to do this is, so Solomon should be able to answer.

Even though #72 open, I don't consider that a blocker for getting the site up by Maker Faire.

# Action

Please discuss this at the next TigerOS meeting (or earlier) and plan to have the website hosted by the Maker Faire.

**Comment by ct-martin** [comment]
@jflory7 Not actually an infrastructure issue, we're going to run it off GitHub Pages (or at least that _was_ the plan...)

Reassign to @axk4545 + you?

**Comment by jflory7** [comment]
We discussed this in the meeting today. I'm waiting for the DNS record to propagate. Planning to have this ready in time for tomorrow, otherwise we'll abandon the subdomain and use the previous set-up. I will close this issue once I have figured out a solution.

**Comment by Tjzabel** [comment]
Website is up! 

Any other information needed or can we close?

**Comment by jflory7** [comment]
Yes, @jflory7 did a dumb and set the record to `ritlug.tigeros.com` instead of `tigeros.ritlug.com`. This is fixed now and the site works as expected! Whooo!

Closing as fixed.
