### ISSUE TITLE
Nicer looking GNOME appearance

### ISSUE THREAD

**Issue by ct-martin** [RITlug/TigerOS#77]
(on behalf of @Tjzabel )

- [x] GNOME Dark Theme by default (arc-dark?)
- [x] Paper icon theme (by default)
- [x] Better/different default font (Overpass?)
- [x] Dash to dock defaults all working

My notes:

- ~Rumor of issues with dark theme and Firefox. Also, does this affect 57?~
- ~Liberation Sans as default Document font~

**Comment by ReginaTL** [comment]
A note on arc dark - it's awesome for the DE stuff but the arc firefox themes are out of date with the new firefox quantum. You would have to use the default theme, which looks much nicer nowadays and uses square tabs, like the arc themes. I forget how I made mine dark sadly.

**Comment by jflory7** [comment]
_Discussed in our [weekly meeting](https://github.com/RITlug/TigerOS/wiki/Next-meeting-agenda)._

## Implementation to be created over break

The next steps for this ticket are to convert the three suggestions above (themes / font) into an implementation in TigerOS. @ct-martin agreed to work on this over break, and then we will review as a team at our first meeting in January to check back in.

**Comment by ct-martin** [comment]
Correction: This falls under @Tjzabel's action item for GNOME, not mine.


--
Christian Martin

**Comment by Tjzabel** [comment]
## Update

GTK Dark theme script has been implemented. Paper icon theme set script has also been created. 
These commits exist on my own [fork](https://github.com/Tjzabel/TigerOS/tree/user-interface/sources/tigeros-scripts/tigeros-scripts-1.0) and are not yet a part of the main TigerOS build. 

We (the TigerOS team) need to decide on the default TigerOS look, where the code for these changes should live, and at what point these changes are to be implemented in the install process.

**Comment by ct-martin** [comment]
@Tjzabel personally have a hard time "seeing" what it looks like from the config files, if you have a screenshot I'd appreciate it. For implementing, this should go in UI-tweaks rather than scripts, and also be part of the package. Also would like to second that we should discuss when we get back.

**Comment by ct-martin** [comment]
I'm going to propose Roboto and Noto Sans as good fonts to replace the default with. I'd also like us to make sure that the default themes aren't removed in the process (removed != !default). @Tjzabel since you have arc-dark working, can you confirm if the dark theme issue affects Firefox 57+? Finally, the comment on Liberation Sans can be ignored, it's no longer a concern for me.

**Comment by Tjzabel** [comment]
@ct-martin Roboto sounds good. And I have used the regular GTK3 dark theme. Feel free to check out my repo [here](https://github.com/Tjzabel/TigerOS/tree/user-interface/sources/tigeros-ui-tweaks). However, I have tested and checked Firefox 57 using the dark theme, and there are no issues with text boxes showing up dark as there has in the past. The default themes are not removed at all, simply changed.

**Comment by ct-martin** [comment]
I would propose moving this to a feature branch in the main repo for the
sake of convenience and clarity ;)


--
Christian Martin

**Comment by Tjzabel** [comment]
@ct-martin I may. For the sake of clarity as well for others, I will probably end up putting the UI improvements into the devel branch to keep our project from getting too many unnecessary branches.

**Comment by ct-martin** [comment]
I am going to maintain that this should be in a feature branch since this
isn't ready for a package yet. I'm going to add this issue to the meeting
on Wednesday and we can discuss it then since this debate probably will be
irrelevant with the new packages.


--
Christian Martin

**Comment by Tjzabel** [comment]
I will want to discuss this. I do not feel it should be in its own branch. However, I currently have UI tweaks in a branch of its own on my own fork [here](https://github.com/Tjzabel/TigerOS/tree/user-interface/sources/tigeros-ui-tweaks/tigeros-ui-tweaks-1.0). 

Good topic for discussion. @ct-martin ++

**Comment by gen1e** [comment]
On cinnamon the dark theme is somewhat broken, fields on web browsers and external programs have problems displaying. We need to check the next time we actually have a build that GNOME doesn't have the same bug.

**Comment by Tjzabel** [comment]
Update: dark-theme and paper icon themes have been tested and are working. Currently awaiting dash-to-dock fixes before making the general UI tweaks considered finished.

**Comment by Tjzabel** [comment]
What exact default font should TigerOS use? @axk4545 @ct-martin

**Comment by ct-martin** [comment]
Roboto, Noto Sans, or Overpass. IIRC we were liking the idea of Overpass at
the last meeting.

On Mar 16, 2018 9:15 PM, "Tim Zabel" <notifications@github.com> wrote:

What exact default font should TigerOS use? @axk4545
<https://github.com/axk4545> @ct-martin <https://github.com/ct-martin>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RITlug/TigerOS/issues/77#issuecomment-373882820>, or mute
the thread

**Comment by Tjzabel** [comment]
Almost done! Changing the default font is the last thing left to do.

**Comment by axk4545** [comment]
@Tjzabel Gonna attempt this.

**Comment by Tjzabel** [comment]
All done!
