### ISSUE TITLE
Make website images same size

### ISSUE THREAD

**Issue by jflory7** [RITlug/TigerOS#81]
# Summary

Make the three logos we use at the bottom of our website (RITlug logo, GitHub, Open Source Initiative) all the same size

# Details

The size of the three images isn't consistent and it makes the spacing a little old when they're viewed horizontally.

![Three images not symmetrical](https://user-images.githubusercontent.com/4721034/32984847-200b8e14-cc7c-11e7-9e19-41168b58db26.png)

The three images should all be the same size so the boxes are symmetrical.

# Action

Set the same width and height on all of the images (or find alternatives for the logos if they don't scale correctly)

**Comment by ct-martin** [comment]
cc #72

**Comment by ct-martin** [comment]
PR didn't autoclose, fixed in #88
