### ISSUE TITLE
Fix website download link

### ISSUE THREAD

**Issue by jflory7** [RITlug/TigerOS#83]
The website's "Download" buttons point to `tigeros.ritlug.com`. Since we moved the site, the downloads are going to be moved elsewhere. The website download buttons should point to the new download source.

**Comment by axk4545** [comment]
This is true. @ct-martin or @jrtechs want to grab this real quick?

Aidan Kahrs
abkahrs@gmail.com

**Comment by axk4545** [comment]
Actually, we decided to leave it until we have a viable download to provide
when @Tjzabel and I talked at makerfaire

Aidan Kahrs
abkahrs@gmail.com

**Comment by jflory7** [comment]
@axk4545 We need to point people somewhere. The link right now points people back to the same page they're on. If we don't want to point people anywhere, then we need to remove the button.

I'm going to link the website in an upcoming article on the Maker Faire, so it's important this is taken care of soon (one way or the other).

**Comment by axk4545** [comment]
Ok. For now let's remove the button and replace it with a note saying they
aren't quite ready yet. Or leave it and point at a simple page with the
same message in the website repo.

Aidan Kahrs
abkahrs@gmail.com

**Comment by jflory7** [comment]
@axk4545 I would opt for removing the button and adding a note to the page saying that ISO downloads are not yet stable.

Keep in mind that this is also a barrier for people who want to test it and see what we're up to. I imagine some people would want to take the ISO to put into a virtual machine and see what we're doing.

**Comment by axk4545** [comment]
@jflory7 getting our most stable ISO up soon and will fix link

**Comment by ct-martin** [comment]
This was fixed with #85

**Comment by jflory7** [comment]
This download button still links to the old domain.

![Download button points to tigeros.ritlug.com](https://screenshots.firefoxusercontent.com/images/30ae3dcb-6c2e-45d8-804e-25b1cf27347a.png)

**Comment by axk4545** [comment]
I think it may have been reverted. Also don't see the new ISO from @jhb2345
up there so I don't know if that was ever uploaded. Once it is up I will
put it in the right place and fix this link.

**Comment by jflory7** [comment]
@axk4545 The "Download" link at the top of the page points to `builder.ritlug.com`, but not the "Download" button in the middle of the page. This should be a 30-60 second fix. But we have the right link and wrong link live on the same page right now.

**Comment by axk4545** [comment]
@jflory7 fixed by latest commit
