### ISSUE TITLE
Add Design Documentation

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/TigerOS#96]
# Summary

* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
Currently there is no documentation for any of our design process. For our wallpaper SVG's, we use the Roboto font, so if others wish to use the svg, but don't have this font installed, this may be an issue.

# Background

### Feature request 

**What does it do?**:
Adds documentation so developers know the extent of the design process.

**Does it need new or changed commands? What are they?**:
No commands need to be changed.

# Details

**Comment by ReginaTL** [comment]
Unless there are any complaints I will put the info in the [TigerOS Development](https://github.com/RITlug/TigerOS/wiki/TigerOS-Development) page in the wiki.

**Comment by ct-martin** [comment]
@ReginaTL Please make a new page and add it to the sidebar, if you need help with this, ping me. Also, if you'd include a note for the location of the `design-assets/` folder with that it contains the project files, as well as where the rendered versions go (aka the backgrounds package), that would be helpful.

**Comment by ct-martin** [comment]
@ReginaTL I was importing some notes into the wiki and created a page for you while I was at it:
https://github.com/RITlug/TigerOS/wiki/TigerOS-Design

**Comment by ReginaTL** [comment]
Okay [take a look](https://github.com/RITlug/TigerOS/wiki/TigerOS-Design) to see if you see any other issues because otherwise I'm pretty sure I got it.

**Comment by ct-martin** [comment]
I see no issues, closing
@gen1e++
