### ISSUE TITLE
Add Vagrantfile for development

### ISSUE THREAD

**Issue by axk4545** [RITlug/TigerOS#98]
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
We should create a Vagrantfile to setup a development environment in a cross-platform way

# Background

### Feature request 

**What does it do?**:
Cross-platform development environment.
**Does it need new or changed commands? What are they?**:
No.
**Does this feature affect other parts of TigerOS?**:
No.

# Details

* **Stacktrace** (if applicable):

**Comment by Tjzabel** [comment]
@axk4545  Has this issue been worked on? I would love to see how Vagrant differs from Docker in terms of development and work flow.

**Comment by axk4545** [comment]
Added in #107
